[package]
name = "nd"
version = "0.1.1"
authors = ["Jeff Dickey <@jdxcode>"]
license = "MIT"
repository = "https://github.com/jdxcode/nd"
description = "library for nd"

[dependencies]
nd_lib = "0.1.0"
