[package]
name = "nd"
version = "0.1.2-alpha.0"
authors = ["Jeff Dickey <@jdxcode>"]
license = "MIT"
repository = "https://github.com/jdxcode/nd"
description = "library for nd"

[dependencies]
nd_lib = "0.1.0"
clap = "2.32.0"
log = "0.4.5"
env_logger = "0.5.13"
